name: build_CLP_win64


on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'upload to artifactory'
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: winfix

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
            zip

      - name: Cache coin-or dependencies
        id: cache-coinor
        uses: actions/cache@v2
        with:
          path:  api/extern/coinor/win64/dist
          key: ${{ runner.os }}-coinor-cbc2.10.8

      - name: build coinor
        shell: msys2 {0}
        working-directory: api/extern/coinor
        if: steps.cache-coinor.outputs.cache-hit != 'true'
        run: |
          export ADD_FFLAGS=-fallow-argument-mismatch
          ./coinbrew build install Cbc@releases/2.10.8 --parallel-jobs $(nproc) --tests none --prefix win64/dist

      - name: build CLPWrapper
        shell: msys2 {0}
        working-directory: api
        run: |
          mkdir build
          cd build
          cmake -G "MSYS Makefiles" -DTARGET_ARCH=64 ..
          cmake --build . --target install

      - name: CLPTest
        working-directory: api/build/test
        shell: msys2 {0}
        run: ./CLPTest

      - name: copy dependencies
        working-directory: api/build/native/w64
        shell: msys2 {0}
        run: |
          ldd CLPModelWrapper_JNI.dll
          cp -v /mingw64/bin/libgfortran-5.dll /mingw64/bin/libgcc_s_seh-1.dll /mingw64/bin/libbz2-1.dll /mingw64/bin/libstdc++-6.dll /mingw64/bin/libgmp-10.dll /mingw64/bin/zlib1.dll /mingw64/bin/libquadmath-0.dll /mingw64/bin/libwinpthread-1.dll .

      - name: upload
        working-directory: api/build/native/
        if: ${{ inputs.upload }}
        shell: msys2 {0}
        run: |
          zipfile=clp_cbc-2.10.8.zip
          url=https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/clp/
          if [[ $(curl -Is $url/$zipfile | head -n 1 | grep -c 'OK') -eq 1 ]]; then
            curl $url/$zipfile -o $zipfile
            zip $zipfile -d 'clp/w64/*' || true # delete old binaries
          fi
          mkdir clp
          cp -r w64 clp/
          zip $zipfile clp/w64/* # insert new ones
          curl --user '${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_TOKEN }}' -X PUT $url -T $zipfile
